/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#define RCC_BASE 0x40023800
#define GPIOC_BASE 0X40020800

#define RCC_AHB1ENR (*(volatile unsigned int *)(RCC_BASE + 0x30))
#define GPIOC_MODER (*(volatile unsigned int *)(GPIOC_BASE + 0x00))
#define GPIOC_ODR (*(volatile unsigned int *)(GPIOC_BASE + 0x14))

void delay(int count){
	for(volatile int i = 0; i < count; i++);
}

int main(void){

	RCC_AHB1ENR |= (1 << 2);

	GPIOC_MODER &=~(3 << 26);
	GPIOC_MODER |= (1 << 26);

	while(1){
		GPIOC_ODR ^= (1 << 13);
		delay(1000);
	}
}
